### ISSUE TITLE
taproot address

### ISSUE THREAD

**Issue by meme20066** [bitmover-studio/bitcoindata#2]
taproot address 
It throws an error while trying to deduce the balance
The script may not read the Taproot's Bitcoin address specifications
Please update the code to read all different Bitcoin addresses

**Comment by bitmover-studio** [comment]
I was not able to reproduce the bug. Looks to be working.

Which addresses do you see the bug?

![image](https://github.com/bitmover-studio/bitcoindata/assets/67111541/4ece997c-39ca-4674-99a3-b5810a366920)

**Comment by meme20066** [comment]
This is amazing
Sorry if I didn't understand the script well
Do you have a video tutorial on how to use it?
